name: Create Release and Publish Package

on:
    workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            VERSION: ${{ steps.extract_version.outputs.VERSION }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies and build
              run: |
                  yarn install --frozen-lockfile
                  yarn build

            - name: Extract version from package.json
              id: extract_version
              run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ steps.extract_version.outputs.VERSION }}
                  name: v${{ steps.extract_version.outputs.VERSION }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: v${{ needs.build.outputs.VERSION }}
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies and build
              run: |
                  yarn install --frozen-lockfile
                  yarn build

            - name: Setup .npmrc
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish to npm
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}